apiVersion: v1
kind: Service
metadata:
  name: alert-service
  namespace: datavisionaries-project
  labels:
    app: alert-service
spec:
  type: ClusterIP
  selector:
    app: alert-service
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http

