apiVersion: v1
kind: Service
metadata:
  name: alert-service
  labels:
    app: alert-service
spec:
  type: LoadBalancer   # or NodePort, LoadBalancer if you want external access
  selector:
    app: alert-service
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
