apiVersion: v1
kind: Service
metadata:
  name: vuln-service
  namespace: datavisionaries-project
  labels:
    app: vuln-service
spec:
  type: ClusterIP
  selector:
    app: vuln-service
  ports:
    - port: 82
      targetPort: 82
      protocol: TCP
      name: http

